### ISSUE TITLE
HBS Helpers not found

### ISSUE THREAD

**Issue by SuchonC** [2110336-SoftwareEngineering2/sec2_Untitled#36]
formatDate
![image](https://user-images.githubusercontent.com/54425973/111408592-15ca4e00-8708-11eb-95ee-4b44aa6c5969.png)
fromNow
![image](https://user-images.githubusercontent.com/54425973/111408637-24b10080-8708-11eb-8263-4527bedbf330.png)

These are where they were called
``` JavaScript
{{#each notifications}}
<img src={{performerPicUrl}} alt="Picture" width="70px">
<p>{{description}}</p>
<p>{{fromNow createDatetime}}</p>
{{/each}}
```
``` JavaScript
<div class="card-text">
<p>From: {{formatDate startDate "DD MMMM YYYY"}}</p>
<p>To: {{formatDate endDate "DD MMMM YYYY"}}</p>
</div>
```
@pabhanuwat Help

**Comment by pabhanuwat** [comment]
Pull main again and see if the problem is fixed

**Comment by SuchonC** [comment]
Thank you, very good
